#!/bin/bash -e
lte() {
    [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
}

lt() {
    [ "$1" = "$2" ] && return 1 || lte $1 $2
}

VER=$1
lt ${VER} 3.0.0 && BRO=bro || BRO=zeek
BUILD_TYPE=${2-Release}

URL=https://download.zeek.org/${BRO}-${VER}.tar.gz

echo VER is $VER
echo URL is $URL

cd /usr/src/
if [ ! -e ${BRO}-${VER}.tar.gz ] ; then 
    wget -c $URL
fi
if [ ! -d ${BRO}-${VER} ]; then
    tar xvzf ${BRO}-${VER}.tar.gz
fi
cd ${BRO}-${VER}
./configure --prefix=/usr/local/${BRO}-${VER} --build-type="${BUILD_TYPE}"
make -j4 install
